name: Koda
version: 0.0.1
schema: v1
models:
- name: Koda Models
provider: koda-chat-models
model: AUTODETECT
roles:
- agent
- chat
- edit
context:
- provider: code
- provider: docs
- provider: diff
- provider: terminal
- provider: problems
- provider: folder
- provider: codebase
mcpServers:
- name: Context Memory
  command: node
  args:
    - /home/vpro3611/context-mcp-server/src/index.js
  env:
    UPSTASH_REDIS_REST_URL: "https://easy-termite-36651.upstash.io"
    UPSTASH_REDIS_REST_TOKEN: "AY8rAAIncDFlODBmMmYxMjVjZDM0ZWQ0YmQzOWU0ZTVjNzMyZTNhZnAxMzY2NTE"
